Namespace(arch='SECA', batch_size=64, bottleneck_dim=64, data='Office31', entropy=False, epochs=20, interpolated=True, iters_per_epoch=500, log='cdan', lr=0.001, lr_decay=0.75, lr_gamma=0.001, momentum=0.9, no_hflip=False, no_pool=False, norm_mean=(0.485, 0.456, 0.406), norm_std=(0.229, 0.224, 0.225), per_class_eval=False, phase='train', print_freq=100, randomized=False, randomized_dim=1024, ratio=[0.75, 1.3333333333333333], resize_size=224, root='test', scale=[0.08, 1.0], scratch=False, seed=0, source=None, target=None, trade_off=1.0, train_resizing='default', trip_time=20, use_unlabel=False, val_resizing='default', weight_decay=0.001, workers=2)
cdan.py:40: UserWarning: You have chosen to seed training. This will turn on the CUDNN deterministic setting, which can slow down your training considerably! You may see unexpected behavior when restarting from checkpoints.
  warnings.warn('You have chosen to seed training. '
All geolife class: {3: 10666, 1: 4078, 0: 7574, 2: 3856}
Train Huawei class: {3: 5045, 1: 5616, 0: 3429, 2: 10997}
Train MTL class: {3: 5045, 1: 5616, 0: 3429, 2: 10997}
Reading Data: (train: geolife + Huawei, test: Huawei)
Total shape: (50174, 248, 6)
GeoLife shape: (26174, 248, 6)
MTL shape: (25087, 248, 6)(6156, 248, 6)
torch.utils.data.dataset.TensorDataset
Traceback (most recent call last):
  File "cdan.py", line 303, in <module>
    main(args)
  File "cdan.py", line 71, in main
    print(train_target_dataset.shape)
  File "/home/xieyuan/anaconda3/envs/Domain-Py36/lib/python3.6/site-packages/torch/utils/data/dataset.py", line 83, in __getattr__
    raise AttributeError
AttributeError
